# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 756)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.Tab = QtWidgets.QWidget()
        self.Tab.setObjectName("Tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.Tab)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 460, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.Tab)
        self.pushButton.setGeometry(QtCore.QRect(170, 460, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Tab)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 10, 281, 541))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkinList = QtWidgets.QListView(self.groupBox_2)
        self.checkinList.setGeometry(QtCore.QRect(0, 20, 281, 521))
        self.checkinList.setObjectName("checkinList")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 490, 591, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 341, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 591, 411))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 611, 451))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget.addTab(self.Tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 531, 361))
        self.label_3.setMaximumSize(QtCore.QSize(640, 480))
        self.label_3.setObjectName("label_3")
        self.checkinList_2 = QtWidgets.QListView(self.tab_2)
        self.checkinList_2.setGeometry(QtCore.QRect(710, 40, 261, 471))
        self.checkinList_2.setObjectName("checkinList_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 490, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 490, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(190, 560, 551, 16))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Training"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.groupBox_2.setTitle(_translate("MainWindow", "List"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Error log"))
        self.label_2.setText(_translate("MainWindow", "Error"))
        self.groupBox.setTitle(_translate("MainWindow", "Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab), _translate("MainWindow", "Runing Mode"))
        self.label_3.setText(_translate("MainWindow", "IMG"))
        self.pushButton_3.setText(_translate("MainWindow", "Training"))
        self.pushButton_4.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "Error"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Training Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
